services:
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=twitter_clone
    ports:
      - "33306:3306"
    restart: unless-stopped
    networks:
      - demo-networks

networks:
    demo-networks:
      external: true