services:
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=twitter_clone
    ports:
      - "33306:3306"
    restart: unless-stopped
    networks:
      - demo-networks

  backend:
    build: ./backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/twitter_clone?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - database
    networks:
      - demo-networks

networks:
  demo-networks:
    external: true
